version: '20.10.21'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/foodgram/foodgram/.env
  web:
    build: .
    restart: always
    expose:
      - 8000:8000
    volumes:
      - static_value:/app/foodgrambackend_static/
      - media_value:/app/foodgrambackend_media/
    depends_on:
      - db
    env_file:
      - ../backend/foodgram/foodgram/.env
  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
      - web
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/foodgrambackend_static/
      - media_value:/app/foodgrambackend_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - db
      - web
      - frontend
    env_file:
      - ../backend/foodgram/foodgram/.env

volumes:
  postgres_data:
  static_value:
  media_value:
