version: '3.3'
services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ../backend/foodgram/foodgram/.env
  foodgram_backend:
    image: freddyandresparraorellana/foodgram_backend:latest
    restart: always
    expose:
      - "8000:8000"
    volumes:
      - static_value:/app/foodgrambackend_static/
      - media_value:/app/foodgrambackend_media/
    depends_on:
      - db
    env_file:
      - ../backend/foodgram/foodgram/.env
  frontend:
    image: freddyandresparraorellana/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - db
      - foodgram_backend
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/app/foodgrambackend_static/
      - media_value:/app/foodgrambackend_media/
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    restart: always
    depends_on:
      - db
      - foodgram_backend
      - frontend
    env_file:
      - ../backend/foodgram/foodgram/.env

volumes:
  postgres_data:
  static_value:
  media_value:
